apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: default
type: Opaque
data:
  MONGO_USERNAME: bW9uZ291c2Vy  # base64 of 'mongouser'
  MONGO_PASSWORD: bW9uZ29wYXNz  # base64 of 'mongopass'